# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import matrix_op_pb2 as matrix__op__pb2


class MatrixOpStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatMult = channel.unary_unary(
                '/MatrixOp/MatMult',
                request_serializer=matrix__op__pb2.OpRequest.SerializeToString,
                response_deserializer=matrix__op__pb2.OpReply.FromString,
                )


class MatrixOpServicer(object):
    """Missing associated documentation comment in .proto file"""

    def MatMult(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixOpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MatMult': grpc.unary_unary_rpc_method_handler(
                    servicer.MatMult,
                    request_deserializer=matrix__op__pb2.OpRequest.FromString,
                    response_serializer=matrix__op__pb2.OpReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MatrixOp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatrixOp(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def MatMult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MatrixOp/MatMult',
            matrix__op__pb2.OpRequest.SerializeToString,
            matrix__op__pb2.OpReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
